config/routes.rb
Rails.application.routes.draw do

  get 'charges/create'

  devise_for :users
  get 'welcome/index'

  resources :wikis do
    resources :collaborators, only: [:create, :destroy]
  end


  resources :users
  resources :welcome, only: [:index, :about]
  resources :charges, only: [:new, :create]

  delete '/downgrade', to: 'charges#downgrade'

  get 'about' => 'welcome#about'

  root 'welcome#index'
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :confirmable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :wikis, through: :collaborators
  has_many :collaborators

  enum role: [:standard, :premium, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :standard
  end

  def standard?
    role == :standard.to_s
  end

  def premium?
    role == :premium.to_s
  end

  def admin?
    role == :admin.to_s
  end

  def downgrade_account
    role = 'standard'
    save
    wikis.where(private: true).update_all(private: false)
  end
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators

  scope :visible_to, -> (user) { publically_viewable }
  scope :publically_viewable, -> { where(private: false) }
  scope :privately_viewable, -> { where(private: true) }

  def collaborator_for(user)
    collaborators.where(user: user).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  protect_from_forgery with: :exception

  private

    def user_not_authorized
      flash[:alert] = "Access denied."
      redirect_to(request.referrer || root_path)
    end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "Membership Upgrade - #{current_user.email}",
      amount: 15_00
    }
  end

  def create
    @user = current_user
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )

    charges = Stripe::Charge.create(
      customer: customer.id,
      amount: 15_00,
      description: "Membership Upgrade - #{current_user.email}",
      currency: 'usd'
    )

    @user.update(role: 'premium')
    flash[:success] = "Thank you for upgrading, #{current_user.email}"
    redirect_to root_path
  end

  def downgrade
    @user = current_user
    @user.downgrade_account
    flash[:alert] = "Downgraded successfully. Please come back again."
    redirect_to root_path
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController

  def create
    @wiki = Wiki.find(params[:wiki_id])
    @collaborator = Collaborator.new(user_id: params[:user_id], wiki_id: params[:wiki_id])

    if @collaborator.save
      flash[:notice] = "You added a collaborator for your wiki."
      redirect_to @wiki
    else
      flash[:error] = "There was an error adding this collaborator. Please try again."
      render :new
    end
  end

  def destroy
    @wiki = Wiki.find(params[:wiki_id])
    @collaborator = Collaborator.find(params[:id])

    if @collaborator.destroy
      flash[:notice] = "Collaborator removed from wiki."
      redirect_to @wiki
    else
      flash[:error] = "There was an error deleting this collaborator. Please try again."
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  after_action :verify_authorized

  def index
    @users = User.all
    authorize User
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def edit
    @users = User.all
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = Wiki.new
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.private = params[:wiki][:private]
    @wiki.user = current_user

    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    @users = User.all
    authorize @wiki
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.private = params[:wiki][:private]
    authorize @wiki
    if @wiki.update(secure_params)
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      redirect_to wiki_path,id: @wiki.id
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    if @wiki.destroy
      flash[:notice] = "Wiki was deleted."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the wiki."
      redirect_to wiki_path,id: @wiki.id
    end
  end

  private

  def secure_params
    params.require(:wiki).permit(:role, :title, :body, :private)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown_to_html(markdown)
    renderer = Redcarpet::Render::HTML.new
    extensions = {fenced_code_blocks: true}
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
    (redcarpet.render markdown).html_safe
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/create.html.erb
<h1>Charges#create</h1>
<p>Find me in app/views/charges/create.html.erb</p>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <h4>Click the button!</h4>
  <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount=<%= @stripe_btn_data[:amount] %> data-description="<%= @stripe_btn_data[:description] %>" ></script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
 <html>
 <head>
   <title>Blocipedia</title>
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <%= stylesheet_link_tag    "application", media: "all" %>
   <%= javascript_include_tag "application" %>
   <%= csrf_meta_tags %>
   <% if user_signed_in? %>
     Signed in as: <strong><%= current_user.email %></strong> |
     <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
   <% else %>
     <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
     <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
   <% end %>
 </head>
 <body>
   <div class="container">
     <ul class="nav nav-tabs">
       <li><%= link_to "Blocipedia", root_path %></li>
       <li><%= link_to "Wikis", wikis_path %></li>
       <li><%= link_to "About", about_path %></li>
     </ul>

     <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
     <% elsif flash.now[:alert] %>
       <div class="alert alert-danger">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash.now[:alert] %>
       </div>
     <% elsif flash[:alert] %>
       <div class="alert alert-warning">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:alert] %>
       </div>
     <% end %>
     <p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>
     <%= yield %>
   </div>

 </body>
 </html>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <td>
    <button><%= f.submit 'Change Role' %></button>
    </td>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="bigbox">
  <div class="box">
    <table class="table-minimal">
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <%= render user %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Email: <%= @user.email if @user.email %></p>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Blocipedia by Mergen</p>

app/views/welcome/index.html.erb
<h1>Welcome to Blocipedia</h1>
<p id="index-title">This is the home page for Bloccit.</p>
<div class="posts">Post 1 goes here.</div>
<div class="posts">Post 2 goes here.</div>
<section>I am the content in a section element.</section>

app/views/wikis/_form_edit.html.erb
<%= form_for @wiki do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
  </div>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
  <% if current_user.admin? || current_user.premium? %>
    <div class="form-group">
      <%= f.label :private, class: 'checkbox' do %>
        <%= f.check_box :private %> Private wiki
      <% end %>
    </div>
  <% end %>
  <% if current_user.premium? %>
  <h3>Collaborators</h3>

  <table class = 'table'>
    <% @users.each do |user| %>
    <tr>
      <td><%= user.email %></td>
      <td>
        <% if @wiki.users.include? user %>
        <%= link_to "Remove Collaborator", [@wiki, @wiki.collaborator_for(user)], method: :delete, class: 'btn btn-danger' %>
        <% else %>
        <%= link_to "Add Collaborator", wiki_collaborators_path(@wiki, user_id: user.id), method: :post, class: 'btn btn-success' %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </table>
  <% end %>
<% end %>

app/views/wikis/_form_new.html.erb
<%= form_for @wiki do |f| %>
 <div class="form-group">
   <%= f.label :title %>
   <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
 </div>
 <div class="form-group">
   <%= f.label :body %>
   <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
 </div>
 <div class="form-group">
   <%= f.submit "Save", class: 'btn btn-success' %>
 </div>
  <% if current_user.admin? || current_user.premium? %>
    <div class="form-group">
      <%= f.label :private, class: 'checkbox' do %>
        <%= f.check_box :private %> Private wiki
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for wikis</p>
    <ul>
      <li>Make sure it rhymes.</li>
      <li>Don't use the letter "A".</li>
      <li>The incessant use of hashtags will get you banned.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= render partial: 'form_edit', locals: { wiki: @wiki } %>
  </div>
</div>

app/views/wikis/index.html.erb
<h1>All Wikis</h1>
  <%= link_to "New", new_wiki_path(@wiki), class: 'btn btn-success' %>
<% @wikis.each do |wiki| %>
<div class="media">
  <div class="media-body">
    <h4 class="media-heading">
      <%= link_to wiki.title, wiki %>
    </h4>
  </div>
</div>
<% end %>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for wikis</p>
    <ul>
      <li>Make sure it rhymes.</li>
      <li>Don't use the letter "A".</li>
      <li>The incessant use of hashtags will get you banned.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= render partial: 'form_new', locals: { wiki: @wiki } %>
  </div>
</div>

app/views/wikis/show.html.erb
<h1><%= markdown_to_html @wiki.title %></h1>

<div class="row">
  <div class="col-md-8">
    <p><%= markdown_to_html @wiki.body %></p>
  </div>
  <div class="col-md-4">
    <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
    <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
   </div>
</div>